PROG = prog
CC = mpic++
CPPFLAGS = -g -Wall
OBJS = PiApproxRSMPIBcast.o

$(PROG) : $(OBJS)
	$(CC) -o $(PROG) $(OBJS)

PiApproxRSMPIBcast.o : PiApproxRSMPIBcast.cpp
	$(CC) $(CPPFLAGS) -c PiApproxRSMPIBcast.cpp

clean:
	rm -f core $(PROG) $(OBJS)

rebuild:
	make clean
	make
